#!/bin/sh

echo "Content-type: text/html"
echo ""

CGI_DIR=/www/cgi-bin
CURRENT_PROXY_TYPE=`cat $CGI_DIR/PROXY_TYPE`
CURRENT_PROXY_IP=`cat $CGI_DIR/PROXY_IP`
CURRENT_PROXY_PORT=`cat $CGI_DIR/PROXY_PORT`
CURRENT_DEVICE_MAC=`cat $CGI_DIR/DEVICE_MAC`

ARGS=`echo "$QUERY_STRING" | tr '&' ' '`

if [ ! -z "$ARGS" ]; then
    $CGI_DIR/firewall.sh $ARGS
    echo '<meta http-equiv="refresh" content="0; url=proxy" />'
fi

echo "<!doctype html>"
echo '<meta name="viewport" content="width=device-width, initial-scale=1">'
echo "<head>"
echo "<style>pre { background: WhiteSmoke; padding: 10px; border-radius: 5px; }</style>"
echo "<title>Proxy Configuration</title>"
echo '<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/css/bootstrap.min.css" integrity="sha384-rwoIResjU2yc3z8GV/NPeZWAv56rSmLldC3R/AZzGRnGxQQKnKkoFVhFQhNUwEyJ" crossorigin="anonymous">'
echo "</head>"

echo "<body>"
echo '<br><div class="container">'
echo "<h3>Proxy Configuration</h3>"
echo "<p>Current Proxy IP: <code>$CURRENT_PROXY_IP</code></p>"
echo "<p>Current Proxy Port: <code>$CURRENT_PROXY_PORT</code></p>"
echo "<p>Current Device MAC: <code>$CURRENT_DEVICE_MAC</code></p>"
#echo "<p><a href=\"http://$CURRENT_PROXY_IP:8081/\">Possible mitmweb instance</a></p>"
echo '<form action="proxy" method="get">'
echo '<fieldset class="form-group">'
echo '<label>Proxy type</label>'
echo '<div class="form-check">'
echo '<label class="form-check-label">'
echo "<input type="radio" class="form-check-input" name="proxy-type" value="full" `[ $CURRENT_PROXY_TYPE = "full" ] && echo "checked"`>full <sup id="sup-1"><a href="#note-1">[1]</a></sup><br>"
echo '</label>'
echo '</div>'
echo '<div class="form-check">'
echo '<label class="form-check-label">'
echo "<input type="radio" class="form-check-input" name="proxy-type" value="partial" `[ $CURRENT_PROXY_TYPE = "partial" ] && echo "checked"`>partial <sup id="sup-2"><a href="#note-2">[2]</a></sup><br>"
echo '</label>'
echo '</div>'
echo '</fieldset>'
echo '<fieldset class="form-group">'
echo '<label for="proxy">Proxy IP</label>'
echo "<input class="form-control" type="text" name="proxy-ip" value="$CURRENT_PROXY_IP">"
echo '</fieldset>'
echo '<fieldset class="form-group">'
echo '<label for="proxy">Proxy Port <sup id="sup-3"><a href="#note-3">[3]</a></sup></label>'
echo "<input class="form-control" type="text" name="proxy-port" value="$CURRENT_PROXY_PORT">"
echo '</fieldset>'
echo '<fieldset class="form-group">'
echo '<label for="mac">Device MAC</label>'
echo "<input class="form-control" type="text" name="mac" value="$CURRENT_DEVICE_MAC">"
echo '</fieldset>'
echo '<fieldset class="form-group">'
echo '<input class="btn btn-primary btn-block btn-large" type="submit">'
echo '</fieldset>'
echo "</form>"
echo "<br><br>"
echo "<p><sup id="note-1"><a href="#sup-1">[1]</a></sup> This is suitable only for mitmproxy or mitmweb running on a Linux or macOS machine.</p>"
echo '<p>For Linux, run the following on the host machine. Replace <code>$INTERFACE</code> with network interface name: 
<pre>sudo iptables -A PREROUTING -t nat -i $INTERFACE -p tcp -m multiport --dports 80,443 -j REDIRECT --to-port 8080</pre><p>'
echo '<p>For mac OS use: <pre>echo "
rdr pass inet proto tcp from any to any port 80 -> 127.0.0.1 port 8080
rdr pass inet proto tcp from any to any port 443 -> 127.0.0.1 port 8080
" | sudo pfctl -ef -</pre><p> '
echo "More info for macOS <a href="https://salferrarello.com/mac-pfctl-port-forwarding/">here</a> and <a href="http://docs.mitmproxy.org/en/stable/transparent/osx.html">here</a>.</p>"
echo "<p>Start mitmproxy with the options <code> --follow -T --host</code>. Add <code> --ignore \.\*:443</code> to ignore SSL traffic.</p>"
echo "<p><sup id="note-2"><a href="#sup-2">[2]</a></sup> Use this for Charles on any OS.</p>"
echo "<p><sup id="note-3"><a href="#sup-3">[3]</a></sup> Only used for <code>Proxy type</code> <code>partial</code>.</p>"
echo "</div>"

echo "</body>"
echo "</html>"
